### ISSUE TITLE
HeaderFooter extension is broken

### ISSUE THREAD

**Issue by vedmaka** [CanastaWiki/Canasta#267]
Enabling `HeaderFooter` on `1.39` leads to

```
[f5aeea3c86c895618bba39ab] /wiki/Main_Page Error: Call to undefined method ParserOptions::getUser()

Backtrace:

from /var/www/mediawiki/w/canasta-extensions/HeaderFooter/HeaderFooter.class.php(12)
#0 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(338): HeaderFooter::hOutputPageParserOutput()
#1 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(137): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#2 /var/www/mediawiki/w/includes/HookContainer/HookRunner.php(2715): MediaWiki\HookContainer\HookContainer->run()
#3 /var/www/mediawiki/w/includes/OutputPage.php(2182): MediaWiki\HookContainer\HookRunner->onOutputPageParserOutput()
#4 /var/www/mediawiki/w/includes/OutputPage.php(2230): OutputPage->addParserOutputMetadata()
#5 /var/www/mediawiki/w/includes/page/Article.php(773): OutputPage->addParserOutput()
#6 /var/www/mediawiki/w/includes/page/Article.php(621): Article->doOutputFromParserCache()
#7 /var/www/mediawiki/w/includes/page/Article.php(528): Article->generateContentOutput()
#8 /var/www/mediawiki/w/includes/actions/ViewAction.php(78): Article->view()
#9 /var/www/mediawiki/w/includes/MediaWiki.php(542): ViewAction->show()
#10 /var/www/mediawiki/w/includes/MediaWiki.php(322): MediaWiki->performAction()
#11 /var/www/mediawiki/w/includes/MediaWiki.php(904): MediaWiki->performRequest()
#12 /var/www/mediawiki/w/includes/MediaWiki.php(562): MediaWiki->main()
#13 /var/www/mediawiki/w/index.php(50): MediaWiki->run()
#14 /var/www/mediawiki/w/index.php(46): wfIndexMain()
#15 {main}
```

**Comment by jeffw16** [comment]
Fixed by #268, closing
