### ISSUE TITLE
mw_sitemap_generator.sh script can't write the sitemap files to the sitemap folder (Permission denied)

### ISSUE THREAD

**Issue by pastakhov** [CanastaWiki/Canasta#315]
The `_sources/scripts/maintenance-scripts/mw_sitemap_generator.sh` script can't write the sitemap files to the sitemap folder (Permission denied):
```
web-1  | PHP Warning:  fopen(/mediawiki/sitemap/sitemap-index-.xml): failed to open stream: Permission denied in /var/www/mediawiki/w/maintenance/generateSitemap.php on line 206
web-1  | PHP Warning:  fwrite() expects parameter 1 to be resource, bool given in /var/www/mediawiki/w/maintenance/generateSitemap.php on line 342
web-1  | 0 ()
web-1  | PHP Warning:  gzopen(/mediawiki/sitemap/sitemap--NS_0-0.xml.gz): failed to open stream: Permission denied in /var/www/mediawiki/w/maintenance/generateSitemap.php on line 430
web-1  | MWException from line 432 of /var/www/mediawiki/w/maintenance/generateSitemap.php: GenerateSitemap::open error opening file /mediawiki/sitemap/sitemap--NS_0-0.xml.gz with flags wb. Check permissions?
web-1  | #0 /var/www/mediawiki/w/maintenance/generateSitemap.php(375): GenerateSitemap->open()
web-1  | #1 /var/www/mediawiki/w/maintenance/generateSitemap.php(207): GenerateSitemap->main()
web-1  | #2 /var/www/mediawiki/w/maintenance/includes/MaintenanceRunner.php(309): GenerateSitemap->execute()
web-1  | #3 /var/www/mediawiki/w/maintenance/doMaintenance.php(85): MediaWiki\Maintenance\MaintenanceRunner->run()
web-1  | #4 /var/www/mediawiki/w/maintenance/generateSitemap.php(590): require_once('/var/www/mediaw...')
web-1  | #5 {main}
```

**Comment by yaronkoren** [comment]
@pastakhov - does this happen every time? And do you have any idea when this problem started to happen?

**Comment by vedmaka** [comment]
this requires a bit more context, what's the mount of the `/mediawiki/sitemap` ? Is this reproducible on https://github.com/CanastaWiki/Canasta-DockerCompose ?
