### ISSUE TITLE
Bootstrap Extension fails to Load

### ISSUE THREAD

**Issue by Byolock** [CanastaWiki/Canasta#58]
I am getting the following error message when activating the bootstrap extension
```
Backtrace:
[8a589b9884d5e54a521b354b] [no req]   RuntimeException from line 142 of /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Hooks/SetupAfterCache.php: Expected an accessible /var/www/mediawiki/w/extensions/Bootstrap/resources/bootstrap path
#0 /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Hooks/SetupAfterCache.php(73): Bootstrap\Hooks\SetupAfterCache->isReadablePath()
#1 /var/www/mediawiki/w/canasta-extensions/Bootstrap/src/Bootstrap.php(62): Bootstrap\Hooks\SetupAfterCache->process()
#2 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(329): Bootstrap\Bootstrap::Bootstrap\{closure}()
#3 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#4 /var/www/mediawiki/w/includes/HookContainer/HookRunner.php(3417): MediaWiki\HookContainer\HookContainer->run()
#7 /var/www/mediawiki/w/maintenance/runJobs.php(129): require_once(string)
#6 /var/www/mediawiki/w/maintenance/doMaintenance.php(91): require_once(string)
#5 /var/www/mediawiki/w/includes/Setup.php(694): MediaWiki\HookContainer\HookRunner->onSetupAfterCache()
```

**Comment by yaronkoren** [comment]
It looks like Bootstrap needs to be added to the "merge-plugin" part of composer.local.json: https://github.com/ProfessionalWiki/Bootstrap#installation

**Comment by yaronkoren** [comment]
...although, thinking about it now, maybe that won't work, and the real solution is to restore the Bootstrap line in the "require" section, which was there before but removed here: https://github.com/CanastaWiki/Canasta/commit/28216453cedd225f38e623df8757cac5790856ab

**Comment by tosfos** [comment]
I assume this PR solves this issue. https://github.com/CanastaWiki/Canasta/pull/71

**Comment by jeffw16** [comment]
#71 merged, closing this issue.
