### ISSUE TITLE
Elastica causing issue

### ISSUE THREAD

**Issue by jeffw16** [CanastaWiki/Canasta#84]
Visiting Special:Version gives this error, probably due to some Composer issue:

```
[eeaa5c0398199830eac77c0f] /wiki/Special:Version Error from line 90 of /var/www/mediawiki/w/canasta-extensions/Elastica/includes/ElasticaConnection.php: Class 'Elastica\Client' not found

Backtrace:

#0 /var/www/mediawiki/w/canasta-extensions/Elastica/includes/ElasticaConnection.php(62): ElasticaConnection->getClient()
#1 /var/www/mediawiki/w/canasta-extensions/CirrusSearch/includes/Connection.php(132): ElasticaConnection->setConnectTimeout()
#2 /var/www/mediawiki/w/canasta-extensions/CirrusSearch/includes/Hooks.php(678): CirrusSearch\Connection->__construct()
#3 /var/www/mediawiki/w/canasta-extensions/CirrusSearch/includes/Hooks.php(365): CirrusSearch\Hooks::getConnection()
#4 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(329): CirrusSearch\Hooks::onSoftwareInfo()
#5 /var/www/mediawiki/w/includes/HookContainer/HookContainer.php(132): MediaWiki\HookContainer\HookContainer->callLegacyHook()
#6 /var/www/mediawiki/w/includes/HookContainer/HookRunner.php(3635): MediaWiki\HookContainer\HookContainer->run()
#7 /var/www/mediawiki/w/includes/specials/SpecialVersion.php(276): MediaWiki\HookContainer\HookRunner->onSoftwareInfo()
#8 /var/www/mediawiki/w/includes/specials/SpecialVersion.php(298): SpecialVersion::getSoftwareInformation()
#9 /var/www/mediawiki/w/includes/specials/SpecialVersion.php(176): SpecialVersion::softwareInformation()
#10 /var/www/mediawiki/w/includes/specialpage/SpecialPage.php(600): SpecialVersion->execute()
#11 /var/www/mediawiki/w/includes/specialpage/SpecialPageFactory.php(635): SpecialPage->run()
#12 /var/www/mediawiki/w/includes/MediaWiki.php(307): MediaWiki\SpecialPage\SpecialPageFactory->executePath()
#13 /var/www/mediawiki/w/includes/MediaWiki.php(945): MediaWiki->performRequest()
#14 /var/www/mediawiki/w/includes/MediaWiki.php(548): MediaWiki->main()
#15 /var/www/mediawiki/w/index.php(53): MediaWiki->run()
#16 /var/www/mediawiki/w/index.php(46): wfIndexMain()
#17 {main}
```

Am using Canasta for Docker Compose 1.0.1

**Comment by jeffw16** [comment]
On second thought, it might be due to the extensions folder being placed at `canasta-extensions/`. The Elastica and CirrusSearch extensions have a bad habit of hardcoding the paths of the locations of files, assuming that they must be stored under `extensions/` and `skins/`.

**Comment by tosfos** [comment]
Please check if this is still an issue after #80

**Comment by tosfos** [comment]
This seems to be fixed
